### PR TITLE
Jbaker/fix off click/#41

### LINKED ISSUE #41: auro-dropdown with toggle attribute doesn't close when clicking off dropdown
## Describe the bug

auro-dropdown with toggle attribute doesn't close when clicking off dropdown

## To Reproduce

1. Go to dropdown demo and scroll to toggle example
1. Click on trigger to open
1. Click away from the dropdown
1. Note the dropdown doesn't close

## Expected behavior

All dropdown examples should close when clicking off the dropdown.

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #41

## Summary:

This change fixes the toggle functionality. Previously, when using the `toggle` attribute you could not click outside the dropdown to close it.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
I reset the base branch to be `jbaker/onDark/#30`, is this the correct diff? The previous PR showed all 50+ files that had been changed in the previous branch.

**Comment by jason-capsule42** [comment]
> I reset the base branch to be `jbaker/onDark/#30`, is this the correct diff? The previous PR showed all 50+ files that had been changed in the previous branch.

@blackfalcon I meant to leave it as draft until after the onDark PR was merged. Fixing this needed to be based off some improvements that were in that branch.

It's now been rebased and is properly ready for review.

**Review by blackfalcon — APPROVED** [review]
This PR is based off of `MAIN`, but seems to be branched off something else. It is sharing all the same updates as PR #30 and there is no way to really tell what this diff is.

**Pull request merged**
