### PR TITLE
Jbaker/slotname/#75

### LINKED ISSUE #75: Slot name inconsistent with other elements
The following slot name is inconsistent with other slot names of similar use 

https://github.com/AlaskaAirlines/auro-dropdown/blob/e1a24170e0c98ff82ccce581a90423e9fe94754c/src/auro-dropdown.js#L26

From auro-input 

https://github.com/AlaskaAirlines/auro-input/blob/a13630541e129ca3bb1f48bc5ce31bf5abdd74a8/src/base-input.js#L39

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #75

## Summary:

This is a version of https://github.com/AlaskaAirlines/auro-dropdown/pull/76/files scaled down to just the slotname changes.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
I don't understand what this PR is? It encompasses all the changes from a previous PR with the additional commit to restore the comments from the README. 

If there is a final decision to remove this from the READMEs, that is a separate commit in a separate PR.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
Do not include the commits from my other PR.

**Comment by jason-capsule42** [comment]
The point of this PR is to undo the changes that you included in the other PR to modify the documentation that is unrelated to the API change. Thats why this PR is just based off the original plus a commit to restore the `generateDocs.js` file and rebuild the docs.

**Comment by blackfalcon** [comment]
The commit in question was removed from https://github.com/AlaskaAirlines/auro-dropdown/pull/76 barring additional discussion about generated documentation management. 

This PR is no longer valid as the code it corrects is no longer there.

**Pull request closed without merging**
