### PR TITLE
refactor(labs): switch from @aurolabs to @aurodesignsystem

### LINKED ISSUE #57: Publish to Auro Design System
# Publish Component

## Specific steps required to publish this component.

1. __Design & Planning__
    - [x] Reviewed [AuroLabs documentation](http://auro.alaskaair.com/)
    - [x] Reviewed [Auro's Contributing Guidelines](http://auro.alaskaair.com/contributing)
    - [x] Reviewed [Auro's CSS conventions](http://auro.alaskaair.com/webcorestylesheets/conventions) and how to apply CSS to custom elements
    - [x] Design team engaged in designing the new component
    - [ ] Design work integrated in the Auro Design System UI Kit
1. __Development__
    - [x] Addresses all design and UX as proposed in the design comp
    - [x] A11y in regards to role and live notifications need to be coded into the final WC
    - [x] All style code follows [Auro's Style Guide](http://auro.alaskaair.com/webcorestylesheets/guidelines)
    - [x] Automated tests created
1. __Documentation__
    - Content Creation
      - [x] `./docs/partials/description.md` content is written.
      - [x] `./docs/partials/useCases.md` content is written.
      - `./docs/partials/demo.md`
        - [x] Basic component examples added to content as imports
        - [x] All examples include rendered example and matching code sample
        - [x] Any scenarios to avoid are outlined in a `Do Not` section
      - `./docs/partials/apiExamples.md`
        - [x] template updated with all component API examples
        - [x] All examples include rendered example and matching code sample
    - Generated docs
      - [x] `./readme.md` compiled
      - [x] `./docs/API.md` compiled and matches API
      - [x] `./demo/demo.md` compiled
      - [x] `./demo/apiExamples.md` compiled
1. __Testing__
    - [x] Component built using latest version of [WC-Generator](http://auro.alaskaair.com/getting-started/developers/generator/install)
    - [x] All automated tests pass and coverage threshold requirements are met
    - [x] [Browser compatibility](http://auro.alaskaair.com/support/browsersSupport) - desktop and mobile versions
    - [Accessibility](http://auro.alaskaair.com/a11y-statement) - One or more of the following
      - [x] Axe / Google Lighthouse (baseline standard)
      - [x] Screenreader (determine usability of experience via screenreader)
      - [x] Keyboard use (a user must be able to navigate to key parts via a keyboard)
      - [x] Accessibility should be verified against all browsers
    - [x] Bundled versions tested
1. __Review__ <br/>
    When the component is ready for a final review it is the responsibility of the contributor to coordinate the following reviews:
    - [x] Reviewed demo with the designer
    - [x] Reviewed demo with Auro Team
    - [x] All work is reviewed by Auro team
1. __Publishing__
    - [ ] Removed all references to `auroLabs` from the repository
    - [x] Component properly named,  e.g. `auro-dropdown`
    - [x] GitHub Repository properly named
    - Updated `readme.md`
      - [ ] Install information updated to published namespace
      - [ ] `Define dependency in project component` updated to published namespace
      - [x] `Bundle example code` updated to published namespace
    - [ ] PR prepared to include demo page in the Auro Doc Site

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #57

## Summary:

Make changes to publish the component to @aurodesignsystem.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Other (publish)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
There shouldn't be any custom padding around the element in the demo. 

Screen Shot 2022-01-06 at 3 41 26 PM

This dismiss button is not working as expected. 

Screen Shot 2022-01-06 at 3 42 35 PM

**Comment by jason-capsule42** [comment]
@blackfalcon Above to comments were resolved and patched in.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
There are a lot of .md files in weird locations. Please review the directories to ensure that there are no duplicate or unnecessary files in this repo. 

Please review https://github.com/AlaskaAirlines/auro-dropdown/tree/jbaker/publish/%2357/apiExamples, examples that are not currently in use maybe move to an alt directory. 

What are files in https://github.com/AlaskaAirlines/auro-dropdown/tree/jbaker/publish/%2357/docs/partials used for? 

What is https://github.com/AlaskaAirlines/auro-dropdown/blob/jbaker/publish/%2357/demo/apiExamples.md for? 

For https://github.com/AlaskaAirlines/auro-dropdown/blob/jbaker/publish/%2357/demo/demo.md please move the examples to below the element info to be in sync with the other element doc pages.

**Review by blackfalcon — APPROVED** [review]
I am approving this PR based on the scope of this PR. I was unaware that the apiExample page was intended to be made public via the doc site, so I created a new issue https://github.com/AlaskaAirlines/auro-dropdown/issues/59 that needs to be resolved prior to the inclusion of this document in the doc site.

**Pull request merged**
